stackprj/stackbase/urls.py
from django.urls import path
from . import views

app_name = 'stackbase'

urlpatterns = [
    path('', views.home, name="home"),
    path('about/', views.about, name="question-lists"),

    # CRUD Function
    path('question/', views.QuestionListView.as_view(), name="question_list"),
    path('question/new/', views.QuestionCreateView.as_view(), name="question_create"),
    path('question/<int:pk>/', views.QuestionDetailView.as_view(),
         name="question_detail"),
    path('question/<int:pk>/update/',
         views.QuestionUpdateView.as_view(), name="question_update"),
    path('question/<int:pk>/delete/',
         views.QuestionDeleteView.as_view(), name="question_delete"),
    path('question/<int:pk>/comment/',
         views.AddCommentView.as_view(), name="question_comment"),
    path('like/<int:pk>', views.like_view, name="like_post")
]

stackprj/stackprj/urls.py
from django.contrib import admin
from django.urls import path, include
from stackusers import views as user_view
from django.contrib.auth import views as auth_view
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('stackbase.urls')),

    # Authentication System

    path('register/', user_view.register, name='register'),
    path('login/', auth_view.LoginView.as_view(template_name='stackusers/login.html'), name='login'),
    path('logout/', auth_view.LogoutView.as_view(template_name='stackusers/logout.html'), name='logout'),

    # Profile
    path('profile/', user_view.Profile, name="profile"),
    path('profile/update/', user_view.profile_update, name="profile_update"),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

stackprj/stackbase/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
# Create your models here.


class Question(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=10000)
    content = models.TextField(null=True, blank=True)
    # content = RichTextField()
    date_created = models.DateTimeField(default=timezone.now())
    likes = models.ManyToManyField(User, related_name='question_post')

    def __str__(self):
        return f'{self.user.username} - Question'

    def get_absolute_url(self):
        return reverse("stackbase:question_detail", kwargs={"pk": self.pk})

    def total_likes(self):
        return self.likes.count()


class Comment(models.Model):
    question = models.ForeignKey(
        Question, related_name="comment", on_delete=models.CASCADE)
    name = models.CharField(max_length=1000)
    content = RichTextField()
    date_created = models.DateTimeField(default=timezone.now())

    def __str__(self):
        return '%s - %s' % (self.question.title, self.question.user)

    def get_absolute_url(self):
        return reverse("stackbase:question_detail", kwargs={"pk": self.pk})

    def save(self, *agrgs, **kwargs):
        super().save(*agrgs, **kwargs)

stackprj/stackbase/forms.py
from .models import Comment
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'content']

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),
        }

stackprj/stackbase/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Question, Comment
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from .forms import CommentForm
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect
# Create your views here.


def home(request):
    return render(request, 'home.html')


def about(request):
    return render(request, 'base.html')


# Crud Function

def like_view(request, pk):
    post = get_object_or_404(Question, id=request.POST.get('question_id'))
    liked = False

    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        liked = False
    else:
        post.likes.add(request.user)
        liked = True
    return HttpResponseRedirect(reverse('stackbase:question_detail', args=[str(pk)]))


class QuestionListView(ListView):
    model = Question
    context_object_name = 'questions'
    ordering = ['-date_created']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        search_input = self.request.GET.get('search-area') or ""

        if search_input:
            context['questions'] = context['questions'].filter(
                title__icontains=search_input)
            context['search_input'] = search_input
        return context


class QuestionDetailView(DetailView):
    model = Question

    def get_context_data(self, *args, **kwargs):
        context = super(QuestionDetailView, self).get_context_data()
        something = get_object_or_404(Question, id=self.kwargs['pk'])
        total_likes = something.total_likes()

        liked = False

        if something.likes.filter(id=self.request.user.id).exists():
            liked = True

        context['total_likes'] = total_likes
        context['liked'] = liked

        return context


class QuestionCreateView(LoginRequiredMixin, CreateView):
    model = Question

    fields = ['title', 'content']
    context_object_name = 'question'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class QuestionUpdateView(UserPassesTestMixin, LoginRequiredMixin, UpdateView):
    model = Question

    fields = ['title', 'content']

    def test_func(self):
        question = self.get_object()
        if self.request.user == question.user:
            return True
        else:
            return False


class QuestionDeleteView(UserPassesTestMixin, LoginRequiredMixin, DeleteView):
    model = Question
    context_object_name = 'question'
    success_url = "/"

    def test_func(self):
        question = self.get_object()
        if self.request.user == question.user:
            return True
        else:
            return False


class CommentDetailView(CreateView):
    model = Comment

    form_class = CommentForm
    template_name = 'stackbase/question_detail.html'

    def form_valid(self, form):
        form.instance.question_id = self.kwargs['pk']

        return super().form_valid(form)

    success_url = reverse_lazy('stackbase:question_detail')


class AddCommentView(CreateView):
    model = Comment
    form_class = CommentForm
    template_name = 'stackbase/question_answer.html'

    def form_valid(self, form):
        form.instance.question_id = self.kwargs['pk']
        return super().form_valid(form)
    success_url = reverse_lazy('stackbase:question_list')

stackprj/stackbase/templates/stackbase/question_answer.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title></title>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;1,100;1,200;1,300;1,400;1,500&display=swap" rel="stylesheet">
        <script src="https://unpkg.com/feather-icons"></script>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200&display=swap" rel="stylesheet">

        <style>
            body {
            background-color: #ffff
            /* background: linear-gradient(230deg, orange 0%, yellow 100%); */

        }

        .padding {
            padding-top: 6rem !important
        }

        .user-card-full {
            overflow: hidden
        }

        .card {
            border-radius: 5px;
            -webkit-box-shadow: 0 1px 20px 0 rgba(69, 90, 100, 0.08);
            box-shadow: 0 1px 20px 0 rgba(53, 53, 53, 0.452);
            border: none;
            margin-bottom: 30px;
        }

        .m-r-0 {
            margin-right: 0px;
        }

        .m-l-0 {
            margin-left: 0px;
        }

        .user-card-full .user-profile {
            border-radius: 5px 0 0 5px;
        }

        .bg-c-lite-green {
            background: -webkit-gradient(linear, left top, right top, from(#f29263), to(#ee5a6f));
            background: linear-gradient(to right, rgb(255, 208, 0), orange);
        }

        .user-profile {
            padding: 20px 0;
        }

        .card-block {
            padding: 1.25rem;
        }

        .m-b-25 {
            margin-bottom: 25px;
        }

        .img-radius {
            border-radius: 100px;
        }
        @media only screen and (min-width: 1400px) {
            .img-radius {
            border-radius: 100px;
        }
        }
        h6 {
            font-size: 13px;
            font-family: 'Poppins', sans-serif;

        }

        .card .card-block p {
            line-height: 25px;
        }

        @media only screen and (min-width: 1400px) {
            p {
                font-size: 14px;
            }
        }

        .card-block {
            padding: 1.25rem;
        }

        .b-b-default {
            border-bottom: 1px solid #e0e0e0;
        }

        .m-b-20 {
            margin-bottom: 20px;
        }

        .p-b-5 {
            padding-bottom: 5px !important;
        }

        .card .card-block p {
            line-height: 25px;
        }

        .m-b-10 {
            margin-bottom: 10px;
        }

        .text-muted {
            color: #919aa3 !important;
        }

        .b-b-default {
            border-bottom: 1px solid #e0e0e0;
        }

        .f-w-600 {
            font-weight: 600;
        }

        .m-b-20 {
            margin-bottom: 20px;
        }

        .m-t-40 {
            margin-top: 20px;
        }

        .p-b-5 {
            padding-bottom: 5px !important;
        }

        .m-b-10 {
            margin-bottom: 10px;
        }

        .m-t-40 {
            margin-top: 20px;
        }

        .user-card-full .social-link li {
            display: inline-block;
        }

        .user-card-full .social-link li a {
            font-size: 20px;
            margin: 0 10px 0 0;
            -webkit-transition: all 0.3s ease-in-out;
            transition: all 0.3s ease-in-out;
        }
        </style>
    </head>
    <body>
        <div class="page-content page-container" id="page-content">
            <div class="padding">
                <div class="row  d-flex justify-content-center">
                    <!-- <div class="col-xl-6 col-md-12"> -->
                        <div class="card user-card-full">
                            <div class="row m-l-0 m-r-0">
                                <div class="col-sm-4 bg-c-lite-green user-profile">
                                    <div class="card-block text-center text-white">
                                        <!-- <div class="m-b-25"> <img src="{{ user.profile.image.url }}" class="img-radius" alt="User-Profile-Image"> </div> -->
                                        <h6 class="f-w-600" style="font-size: 24px; color: black;">Answer a question here!</h6>
                                        <p style="font-size: 14px; color: black;">...your contribution really matters to us tech guys!!</p> <i class=" mdi mdi-square-edit-outline feather icon-edit m-t-10 f-16"></i>
                                    </div>
                                </div>
                                <div class="col-sm-8">
                                    <div class="card-block">
                                        </div>
                                        
                                        <form action="" method="POST">
                                            {% csrf_token %}
                                            {% comment %} {{form|crispy}} {% endcomment %}
                                            {{form.name}}
                                            {{form.content | safe}}
                                            {{ form.media }}
                                            <button class="btn btn-success" id="logout-btn" type="submit">Post Answer</button>
                                            <a style="text-decoration: none; " class="btn btn-outline-secondary" href="{%url 'stackbase:question_list'%}">Cancel</a>
                                        </form>


                                        
                                        <div style="margin-top: 10px;">
                                            
                                        </div>
                                        <ul class="social-link list-unstyled m-t-40 m-b-10">
                                            <li><a href="#!" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="facebook" data-abc="true"><i class="mdi mdi-facebook feather icon-facebook facebook" aria-hidden="true"></i></a></li>
                                            <li><a href="#!" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="twitter" data-abc="true"><i class="mdi mdi-twitter feather icon-twitter twitter" aria-hidden="true"></i></a></li>
                                            <li><a href="#!" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="instagram" data-abc="true"><i class="mdi mdi-instagram feather icon-instagram instagram" aria-hidden="true"></i></a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <script>
            feather.replace()
          </script>
    </body>
    </html>
{% endblock content %}

stackprj/stackbase/templates/stackbase/question_detail.html
{% extends 'base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;1,100;1,200;1,300;1,400;1,500&display=swap" rel="stylesheet">
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous"> -->
    <style>
        body{
            margin-top: 100px;
            font-family: 'Poppins', sans-serif;
        }
        #fh1{
            margin-top: 20px;
        }
        #sub-nav{
            display: flex;
            justify-content: space-around;
        }
        #logout-btn{
            background-color: rgb(50, 122, 255);
        }
        /* .list-question{
            height: 400px;
            background-color: rgb(255, 219, 173);
        } */
        #fh3{
            text-align: center;
            font-size: 30px;
            padding-top: 20px;
            text-align: left;
        }
        @media screen and (max-width: 600px) {
            #fh3{
                font-size: 17px;
                text-align: left;
            }
        }
        #fh6{
            text-align: left;
            font-size: 15px;
            /* padding-top: 20px; */
            padding-bottom: 20px;
            font-weight: normal;
        }
        @media screen and (max-width: 600px) {
            #fh6{
                font-size: 15px;
                text-align: left;
                font-weight: normal;
            }
        }
        #fh5{
            display: flex;
            justify-content: space-around;
            text-align: left;
            font-size: 13px;
            padding-top: 3px;
            width: 90px;
            color: rgb(223, 223, 223);
            height: 20px;
            font-weight: normal;
            background-color: rgb(158, 158, 158);
            border-radius: 20px;
            /* padding-top: 20px; */
            /* background-color: blue; */
        }
        @media screen and (max-width: 600px) {
            #fh5{
                font-size: 10px;
            }
        }
        
    </style>
</head>
<body>
    <div class="container">
        <div id="sub-nav">
            <!-- <h1 id="fh1">Hey Guys, Let's help :)</h1> -->
            <!-- <button class="btn" id="logout-btn"><a id="fa" href="" style="color: white; text-decoration: none;">Ask Question</a></button> -->

            <!-- <div style="margin-top: 55px;">
                <button class="btn btn-primary" id="logout-btn"><a id="fa" href="" style="color: white; text-decoration: none;">Ask Question</a></button>
            </div> -->
        </div>
        <div class="list-question">
            <div class="questions">
                <div class="container" style="background-color: rgba(255, 235, 209, 0.808); padding: 5px; box-shadow: rgba(0, 0, 0, 0.15) 0px 5px 5px 0px; border-radius: 20px;" >
                    <h3 id="fh3">{{question.title}}</h3>
                    <hr>
                    <h6 id="fh6">{{ question.content|safe}}</h6>
                    <hr>
                    <h6 id="fh6" style="font-size: 10px; font-style: italic; color: rgb(155, 155, 155); text-align: right;">Asked By: <a href="{% url 'profile' %}">{{ object.user|title }}</a>&nbsp;&nbsp;&nbsp; |&nbsp;&nbsp;&nbsp; On: {{ object.date_created|date:"j F, Y" }}</h6>
                    
                    <br>
                        <form action="{%url 'stackbase:like_post' object.pk %}" method="POST">
                            {% csrf_token %}
                            
                            {% if user.is_authenticated %}
                                {% if liked %}
                                    <div style="display: flex; align-items: center; margin-left: 10px;">
                                        <button type="submit" name="question_id" value="{{ question.id }}" style="border: none; border-radius: 60px;"><img src="https://image.similarpng.com/very-thumbnail/2020/06/Dislike-icon-transparent-PNG.png" alt="" style="width: 40px;"></button> <h5 style="margin-left: 10px; cursor: pointer;"> |  {{ total_likes }} Likes</h5>
                                    </div>
                                {% else %}
                                    <div style="display: flex; align-items: center; margin-left: 10px;">
                                        <button type="submit" name="question_id" value="{{ question.id }}" style="border: none; border-radius: 30px;"><img src="https://i.pinimg.com/originals/39/44/6c/39446caa52f53369b92bc97253d2b2f1.png" alt="" style="width: 40px;"></button> <h5 style="margin-left: 10px; cursor: pointer;"> |  {{ total_likes }} Likes</h5>
                                    </div>
                                {% endif %}
                            {% else %}
                                <h5 style="margin-left: 10px; cursor: pointer;"><a href="{% url 'login' %}">Login</a> to Like Question |  {{ total_likes }} Likes</h5>
                            {% endif %}

                        </form>
                    <br>
                    <h2>Answers...</h2> <br><br><br>

                    {% if not question.comment.all %}
                        <h3>No Answers yet... <a href="">Answer Question</a> </h3>
                    {% else %}
                        {% for comment in question.comment.all %}
                        
                            <h3 style="font-weight: normal; font-size: 15px;">{{comment.content|safe}}</h3>
                            <h3 style="font-size: 10px;">Answered by: <i><a href="">{{comment.name}}</a> - On: {{ comment.date_created | date:"j F, Y"}}</i></h3>
                            <hr>  
                        {% endfor %}
                    {% endif %}



                    <!-- {% if not questions.comments.all %}
                        <h3>No Answers yet... <a href="">Answer Question</a> </h3>
                    {% else %}

                        {% for comment in questions.comments.all %}
                            <h3 style="font-weight: normal; font-size: 15px;">{{comment.body|safe}}</h3>
                            <h3 style="font-size: 10px;">Answered by: <i><a href="">{{comment.name}}</a> - {{comment.date_added|date:"j F, Y"}}</i></h3>
                            <hr>    
                        {% endfor %}
                    {% endif %}

                    <br><br><br><br><br><br>

                    <form action="" method="POST">
                        {% csrf_token %}
                        {% if user.is_authenticated %}
                        {% if liked %}
                            <div style="display: flex; align-items: center; margin-left: 10px;">
                                <button type="submit" name="questions_id" value="{{ questions.id }}" style="border: none; border-radius: 60px;"><img src="https://image.similarpng.com/very-thumbnail/2020/06/Dislike-icon-transparent-PNG.png" alt="" style="width: 40px;"></button> <h5 style="margin-left: 10px; cursor: pointer;"> |  {{ total_likes }} Likes</h5>
                            </div>
                        {% else %}
                            <div style="display: flex; align-items: center; margin-left: 10px;">
                                <button type="submit" name="questions_id" value="{{ questions.id }}" style="border: none; border-radius: 30px;"><img src="https://i.pinimg.com/originals/39/44/6c/39446caa52f53369b92bc97253d2b2f1.png" alt="" style="width: 40px;"></button> <h5 style="margin-left: 10px; cursor: pointer;"> |  {{ total_likes }} Likes</h5>
                            </div>
                        {% endif %}
                        {% else %}
                            <h5 style="margin-left: 10px; cursor: pointer;"><a href="{% url 'login' %}">Login</a> to Like Question |  {{ total_likes }} Likes</h5>
                        {% endif %}
                    </form> -->
                    
                    <a class="btn btn-outline-primary" id="fa" href="{% url 'stackbase:question_comment' question.id %}" style="text-decoration: none;">Answer Question</a>
                    <a style="text-decoration: none; " class="btn btn-outline-success" href="{% url 'stackbase:question_update' question.id %}">&#x270E;</a>
                    <a style="text-decoration: none; " class="btn btn-outline-danger" href="{% url 'stackbase:question_delete' question.id %}">&#x2716;</a>
                    <a style="text-decoration: none; " class="btn btn-outline-secondary" href="{% url 'stackbase:question_list' %}">&#x21a9;</a>
                </div> <br><br>
                    <!-- Answer Section -->
                
                </div> <br>
            </div>
        </div>
        <br>
        
    </div>
    <!-- <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-W8fXfP3gkOKtndU4JGtKDvXbO53Wy8SZCQHczT5FMiiqmQfUpWbYdTil/SxwZgAN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js" integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/" crossorigin="anonymous"></script> -->
</body>
</html>
{% endblock content %}

stackprj/stackbase/templates/stackbase/question_list.html
{% extends 'base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;1,100;1,200;1,300;1,400;1,500&display=swap" rel="stylesheet">
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous"> -->
    <style>
        body{
            margin-top: 100px;
            font-family: 'Poppins', sans-serif;
        }
        #fh1{
            margin-top: 20px;
        }
        #sub-nav{
            display: flex;
            justify-content: space-around;
        }
        #logout-btn{
            background-color: rgb(50, 122, 255);
        }
        #fh3{
            text-align: left;
            font-size: 19px;
            padding-top: 15px;
        }
        @media screen and (max-width: 600px) {
            #fh3{
                font-size: 15px;
                text-align: left;
            }
        }
        #fh6{
            text-align: right;
            font-size: 15px;
            /* padding-bottom: 20px; */
            font-weight: normal;
        }
        @media screen and (max-width: 600px) {
            #fh6{
                font-size: 15px;
                text-align: right;
                font-weight: normal;
            }
        }
        #fh5{
            display: flex;
            justify-content: space-around;
            text-align: left;
            font-size: 13px;
            padding-top: 3px;
            width: 90px;
            color: rgb(223, 223, 223);
            height: 20px;
            font-weight: normal;
            background-color: rgb(158, 158, 158);
            border-radius: 20px;
            /* padding-top: 20px; */
            /* background-color: blue; */
        }
        @media screen and (max-width: 600px) {
            #fh5{
                font-size: 10px;
            }
        }
        a{
            color: rgb(0, 132, 255);
        }
        a:hover{
            text-decoration: none;
            color: darkblue;
            
        }
        h5{
            color: rgb(133, 133, 133);
        }
    </style>
</head>
<body>
    <div class="container">
        <div id="sub-nav">
            <h1 id="fh1">Top Questions</h1>
            {%if user.is_authenticated%}
            <button class="btn" id="logout-btn"><a id="fa" href="{% url 'stackbase:question_create'%}" style="color: white; text-decoration: none;">Ask Question</a></button>
            {% else %}
            <button class="btn" id="logout-btn"><a id="fa" href="{% url 'login' %}" style="color: white; text-decoration: none;">Ask Question</a></button>
            {%endif%}
        </div>
        <div class="list-question">
            <div class="questions">
                {% for question in questions %}
                <div class="container" style="background: linear-gradient(to right, rgb(255, 226, 182), rgba(255, 166, 0, 0.027)); padding: 5px; box-shadow: rgba(0, 0, 0, 0.383) 0px 5px 5px 0px; border-radius: 15px;" >
                    <div id="title-sec" style="display: flex; align-items: center;">
                        <!-- <a href="{% url 'profile' %}"><img src="{{ request.user.profile.image.url }}" style="width: 50px;"></a></img> -->
                        <h3 id="fh3"><a href="{% url 'stackbase:question_detail' question.id %}">{{question.title}}</a></h3>
                    </div>
                    <hr>
                    {% if question.content|wordcount <= 10%}
                    <h6 id="fh6" style="text-align: left;">{{ question.content | safe}}</h6>
                    {% else %}
                    <h6 id="fh6" style="text-align: left;">{{ question.content|truncatewords:10}} <a href="{% url 'stackbase:question_detail' question.id%}">Read More</a></h6>
                    {% endif %}
                    <h6 id="fh6" style="font-size: 10px; font-style: italic; color: rgb(155, 155, 155);">Asked By: <a href="{% url 'profile' %}">{{ question.user }}</a>&nbsp;&nbsp;&nbsp; |&nbsp;&nbsp;&nbsp; On: {{question.date_created|date:"j F, Y"}}</h6>
                    <h5 style="text-align: right; font-size: 12px; font-style: italic;">Tags</h5>
                </div> <br>
                
            </div>
            {%  endfor %}
        </div>   
    </div>
</body>
</html>
{% endblock content %}